//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kabel.DemoWPF.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
	public partial class Shipper
    {
        public Shipper()
        {
            this.Orders = new HashSet<Order>();
        }
    
        [DataMember]
		public int ShipperID { get; set; }
        [DataMember]
		public string CompanyName { get; set; }
        [DataMember]
		public string Phone { get; set; }
    
        [DataMember]
		public virtual ICollection<Order> Orders { get; set; }
    }
}
